# Generated by Django 5.2 on 2025-04-21 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertease', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='freelancers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('place', models.CharField(max_length=20)),
                ('subcategoryname', models.CharField(max_length=20)),
                ('specilization', models.CharField(max_length=30)),
                ('bi', models.CharField(max_length=100)),
                ('image', models.FileField(null=True, upload_to='img')),
                ('wi', models.CharField(max_length=100)),
                ('wimage', models.FileField(null=True, upload_to='img')),
                ('cn', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('categoryname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expertease.category')),
            ],
        ),
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategorynm', models.CharField(max_length=20)),
                ('categorynm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expertease.category')),
            ],
        ),
    ]
