# Generated by Django 5.2 on 2025-04-21 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expertease', '0002_freelancers_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancers',
            name='subcategoryname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expertease.subcategory'),
        ),
    ]
